# Generated by Django 5.1.1 on 2024-09-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_is_admin_delete_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
