# Generated by Django 5.1 on 2024-09-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_invite'),
        ('users', '0007_userprofile_can_add_userprofile_can_view'),
    ]

    operations = [
    ]
