# Generated by Django 5.1.1 on 2024-11-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_entry_group_alter_entry_user_filter'),
        ('users', '0008_merge_20240929_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='group',
        ),
        migrations.AddField(
            model_name='entry',
            name='groups',
            field=models.ManyToManyField(related_name='entries', to='users.group'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='filters', to='users.group'),
        ),
    ]
